package app.cicilan.di

import android.app.Application
import androidx.datastore.preferences.core.PreferenceDataStoreFactory
import androidx.datastore.preferences.preferencesDataStoreFile
import androidx.room.Room
import app.cicilan.db.CicilanDb
import app.cicilan.preference.StoreData
import app.cicilan.repositories.CicilanLogRepository
import app.cicilan.repositories.CicilanRepository
import app.cicilan.repositories.CicilanViewerRepository
import app.cicilan.usecases.CountCicilanUseCase
import app.cicilan.usecases.GetListCicilanLogUseCase
import com.google.android.material.color.DynamicColors
import id.arizona.repository.CicilanLogRepoImpl
import id.arizona.repository.CicilanRepoImpl
import id.arizona.repository.CicilanViewerRepoImpl
import org.koin.android.ext.koin.androidContext
import org.koin.core.context.startKoin
import org.koin.dsl.module
